services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  rag-network:
    external: true